spring:
  db1:
    datasource:
      jdbc-url: jdbc:mysql://10.8.180.139:13306/demo041?useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: user01
      password: user01
  db2:
    datasource:
      jdbc-url: jdbc:mysql://10.8.180.139:13306/demo042?useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: user01
      password: user01
  db3:
    datasource:
      jdbc-url: jdbc:mysql://10.8.180.139:13306/demo043?useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: user01
      password: user01      