spring:
  first:
    datasource:
      jdbc-url: jdbc:mariadb://192.168.100.100:13306/demo
      driver-class-name: org.mariadb.jdbc.Driver
      username: user01
      password: user01
  second:
    datasource:
      jdbc-url: jdbc:mariadb://192.168.100.100:13306/demo2
      driver-class-name: org.mariadb.jdbc.Driver
      username: user01
      password: user01