spring:
  first:
    datasource:
      jdbc-url: jdbc:mysql://localhost:13306/demo03?useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: user01
      password: user01
  second:
    datasource:
      jdbc-url: jdbc:mysql://localhost:13306/demo04?useSSL=false&serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: user01
      password: user01
