server:
  port: 8300
spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
    url: jdbc:mysql://10.8.180.139:13306/demo03?useSSL=false&serverTimezone=Asia/Seoul
    username: user01
    password: user01
  session:
    store-type: REDIS
  redis:    host: 10.8.180.139
    port: 6379