server:
  port: 8300
spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:13306/demo03?useSSL=false&serverTimezone=Asia/Seoul
    username: user01
    password: user01
  session:
    store-type: REDIS
  redis:    host: localhost
    port: 6379
