server:
  port: 8300
spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://192.168.100.100:13306/demo
    username: user01
    password: user01
    driver-class-name: org.mariadb.jdbc.Driver
  session:
    store-type: REDIS
  redis:
    host: 192.168.100.100
    port: 6379